kind: DataPowerAssembly
apiVersion: api.ibm.com/v1
metadata:
  name: invoke
  namespace: BE_PR_BANK
  version: '1.0'
  tags: []
  labels:
    gatewayTypes:
      - datapower
spec:
  x-ibm-configuration:
    enforced: true
    testable: true
    phase: realized
    gateway: datapower-api-gateway
    assembly:
      execute:
        - invoke:
            version: 2.3.0
            title: invoke
            backend-type: detect
            header-control:
              type: blocklist
              values: []
            parameter-control:
              type: allowlist
              values: []
            http-version: HTTP/1.1
            timeout: 60
            verb: keep
            chunked-uploads: true
            persistent-connection: true
            cache-response: protocol
            cache-ttl: 900
            websocket-upgrade: false
            graphql-send-type: detect
            target-url: >-
              https://sample-api.us-east-a.apiconnect.automation.ibm.com/bank/branches
