openapi: 3.0.0
info:
  title: order-management-api
  version: 1.0.0
  description: >-
    The order-management-api allows for the management of customer orders,
    including retrieval, creation, updates, and deletion.
  contact: {}
paths:
  /orders:
    get:
      summary: Retrieve a list of all orders
      responses:
        '200':
          description: A list of orders
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Order'
        '400':
          description: Bad request
        '500':
          description: Internal server error
      operationId: retrieve-list-orders
      description: >-
        This operation retrieves all orders available in the order management
        system.
      tags:
        - orders
    post:
      summary: Create a new order
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Order'
      responses:
        '201':
          description: Order created
        '400':
          description: Bad request
        '500':
          description: Internal server error
      operationId: create-new-order
      description: >-
        This operation allows for adding a new order to the order management
        system.
      tags:
        - orders
  /order/{id}:
    get:
      summary: Retrieve a specific order by its ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: The requested order
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Order'
        '400':
          description: Bad request
        '404':
          description: Order not found
        '500':
          description: Internal server error
      operationId: retrieve-specific-order-its-id
      description: >-
        This operation retrieves detailed information for a specific order using
        its unique order ID.
      tags:
        - orders
    put:
      summary: Update an existing order
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Order'
      responses:
        '200':
          description: Order updated
        '400':
          description: Bad request
        '404':
          description: Order not found
        '500':
          description: Internal server error
      operationId: update-existing-order
      description: >-
        This operation allows for updating an existing order in the order
        management system.
      tags:
        - orders
    delete:
      summary: Delete an order
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Order deleted
        '400':
          description: Bad request
        '404':
          description: Order not found
        '500':
          description: Internal server error
      operationId: delete-order
      description: >-
        This operation allows for deleting an order from the order management
        system.
      tags:
        - orders
components:
  schemas:
    Order:
      type: object
      properties:
        Id:
          type: string
        Product:
          type: string
        ProductCode:
          type: string
        orderdate:
          type: string
        quantity:
          type: integer
        price:
          type: number
        description:
          type: string
      required:
        - Id
        - Product
        - ProductCode
        - orderdate
        - quantity
        - price
        - description
servers:
  - url: /productorders
tags:
  - name: orders
    description: 'product order'
