openapi: 3.0.0
info:
  title: rest-api-example
  version: 1.0.0
servers:
  - url: https://api.example.com
paths:
  /resource:
    get:
      summary: Get all resources
      responses:
        '200':
          description: A list of resources
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Resource'
        '401':
          description: Unauthorized
        '500':
          description: Internal Server Error
      operationId: get-resources
    post:
      summary: Create a new resource
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Resource'
      responses:
        '201':
          description: Resource created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Resource'
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '500':
          description: Internal Server Error
      operationId: create-new-resource
  /resource/{paramName}:
    parameters:
      - name: paramName
        in: path
        required: true
        schema:
          type: string
    get:
      summary: Get a resource by id
      responses:
        '200':
          description: A resource
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Resource'
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '404':
          description: Resource not found
        '500':
          description: Internal Server Error
      operationId: get-resource-id
    put:
      summary: Update a resource by id
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Resource'
      responses:
        '200':
          description: Resource updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Resource'
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '404':
          description: Resource not found
        '500':
          description: Internal Server Error
      operationId: update-resource-id
    delete:
      summary: Delete a resource by id
      responses:
        '204':
          description: Resource deleted
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '404':
          description: Resource not found
        '500':
          description: Internal Server Error
      operationId: delete-resource-id
  /user:
    get:
      summary: Get all users
      responses:
        '200':
          description: A list of users
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
        '401':
          description: Unauthorized
        '500':
          description: Internal Server Error
      operationId: get-users
    post:
      summary: Create a new user
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        '201':
          description: User created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '500':
          description: Internal Server Error
      operationId: create-new-user
components:
  schemas:
    Resource:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        description:
          type: string
      required:
        - id
        - name
    User:
      type: object
      properties:
        id:
          type: string
        username:
          type: string
        email:
          type: string
        password:
          type: string
      required:
        - id
        - username
        - email
        - password
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
security:
  - bearerAuth: []
